version: '2'

services:
  minio:
    image: minio/minio
    container_name: trdl_minio
    ports:
      - 9000:9000
    command: server /data
    volumes:
      - ./.minio_data:/data

  mc:
    image: minio/mc
    depends_on:
      - minio
    container_name: trdl_mc
    environment:
      MC_HOST_main: http://minioadmin:minioadmin@minio:9000
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc mb main/test-project;
      /usr/bin/mc policy set download main/test-project;
      "