topnav_title: trdl
site_title: trdl
company_url:
  ru: https://flant.ru
  en: https://flant.com
company_name:
  ru: Флант
  en: Flant
site_lang: en
site_urls:
  ru: ru.trdl.dev
  en: trdl.dev
site_description: Deliver your software continuously & securely.
github_repo_path: /werf/trdl

exclude:
- .gitignore
- Gemfile
- Gemfile.lock
- werf.yaml
- pages_ru/

highlighter: rouge

plugins:
- jekyll-assets
#- jekyll-remote-theme

assets:
#  precompile: ['**/*.*']
  sources:
    - assets/js
    #- _tmp_dir/cc/js
    #- /home/kar/.gem/bundle/ruby/2.7.0/bundler/gems/website-core-cafff16c4189/assets/js
markdown: kramdown
kramdown:
 input: GFM
 hard_wrap: false
 syntax_highlighter: rouge

breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text
  hometext: "Home"

collections:
  tooltips:
    output: false

#remote_theme:  https://github.com/flant/website-core@dev
theme:  flant-theme

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      search: true
      sidebar: false
      topnav: topnav
      sitemap_include: true
      multilang: true
  - scope:
      path: "pages_*/reference"
      type: "pages"
    values:
      sidebar: reference
  - scope:
      path: "pages_*/reference/cli"
      type: "pages"
    values:
      toc: false
  - scope:
      path: "pages_*/reference/vault_plugin/*"
      type: "pages"
    values:
      toc: true
  - scope:
      path: "pages_*/reference/vault_plugin/index.md"
      type: "pages"
    values:
      toc: false

timezone: Etc/GMT-3
output: web
