name: CLI and API partials checker
on:
  push:
    paths:
      - '.github/workflows/docs_cli_and_api_partials_checker.yml'
      - 'client/cmd/**'
      - 'server/**'

jobs:
  check:
    name: Partials checker
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: Install werf build dependencies
        run: sudo apt-get install -y libbtrfs-dev

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Prepare environment
        run: ./e2e/scripts/ci/git.sh

      - name: Regen partials
        working-directory: docs
        run: make

      - name: Check
        run: |
          git add -A
          git diff --exit-code HEAD -- || { echo -e "CLI or API partials are outdated!\nRegen it with 'make -C docs' and then commit changes."; exit 1; }
