name: Test and coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Test and coverage
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=readonly
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test ${{ matrix.plugin }}
        run: go test -vet=off -coverpkg=./... -coverprofile coverage.out ./...

      - name: Install coverage reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Format and publish coverage
        run: |
          export GIT_BRANCH=${GITHUB_REF:11}
          export GIT_COMMIT_SHA=$GITHUB_SHA

          ./cc-test-reporter format-coverage \
              -t=gocov \
              -p=github.com/werf/vault-plugin-secrets-trdl/ \
              coverage.out

          ./cc-test-reporter upload-coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
